version: '3.9'
services:
  db:
    image: mysql:8.0.31
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: Angelo_89212532
      MYSQL_USER: root
      MYSQL_PASSWORD: Angelo_89212532
      MYSQL_DATABASE: spring-aws-docker
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - erudio-network
  spring-aws-docker:
    image: angelolop/spring-aws-docker
    restart: always
    build: ./spring-aws-docker
    working_dir: /C:/Users/angelo/Desktop/Estudos/Java/spring-aws-docker-with-compose/spring-aws-docker
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/spring-aws-docker
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: Angelo_89212532
    ports:
      - "8082:8082"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - erudio-network
networks:
  erudio-network:
    driver: bridge