server:
  port: 8082

cors:
  originPatterns: http://localhost:8081,https://erudio.com.br,http://localhost:3000

file:
  upload-dir: /Users/angelo/Desktop

security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000

spring:
  datasource:
    url: jdbc:mysql://spring-aws-docker.cjava4dxjz7k.us-east-1.rds.amazonaws.com:3306/spring_aws_docker
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: docker
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
spring-doc:
  pathsToMatch:
    - /auth/**
    - /**/v1/**
  swagger-ui:
    use-root-path: true
